CREATE TABLE US_Companies(
    Ticker VARCHAR(250),
    Company_ID INT PRIMARY KEY,
    Company_Name VARCHAR(250),
    Industry_ID INT,
    ISIN VARCHAR(250),
    End_of_financial_year_month INT,
    Number_Employees INT,
    Business_Summary VARCHAR(8000),
    Market VARCHAR(250),
    CIK INT,
    Main_Currency VARCHAR(10)
);

CREATE TABLE Income_Statement(
    Ticker VARCHAR(250),
    Company_ID INT,
    Currency VARCHAR(10),
    Fiscal_Year INT,
    Fiscal_Period VARCHAR(2),
    Report_Date DATE,
    Publish_Date DATE,
    Restated_Date DATE,
    Basic_Shares BIGINT,
    Diluted_Shares BIGINT,
    Revenue NUMERIC,
    Cost_of_Revenue NUMERIC,
    Gross_Profit NUMERIC,
    Operating_Expenses NUMERIC,
    Selling_General_and_Administrative NUMERIC,
    Research_and_Development NUMERIC,
    Depreciation_and_Amortization NUMERIC,
    Operating_Income NUMERIC,
    Non_Operating_Income NUMERIC,
    Interest_Expense_Net NUMERIC,
    Pretax_Income_Adj NUMERIC,
    Abnormal_Gains NUMERIC,
    Pretax_Income NUMERIC,
    Income_Tax_Benefit_Net NUMERIC,
    Income_from_Continuing_Operations NUMERIC,
    Net_Extraordinary_Gains NUMERIC,
    Net_Income NUMERIC,
    Net_Income_Common NUMERIC,
    FOREIGN KEY (Company_ID) REFERENCES US_Companies (Company_ID)
);

CREATE TABLE Balance_Sheet(
    Ticker VARCHAR(250),
    Company_ID INT,
    Currency VARCHAR(10),
    Fiscal_Year INT,
    Fiscal_Period VARCHAR(2),
    Report_Date DATE,
    Publish_Date DATE,
    Restated_Date DATE,
    Basic_Shares BIGINT,
    Diluted_Shares BIGINT,
    Cash_Cash_Equivalents_and_Short_Term_Investments NUMERIC,
    Accounts_and_Notes_Receivable NUMERIC,
    Inventories NUMERIC,
    Total_Current_Assets NUMERIC,
    Property_Plant_and_Equipment_Net NUMERIC,
    Long_Term_Investments_and_Receivables NUMERIC,
    Other_Long_Term_Assets NUMERIC,
    Total_Noncurrent_Assets NUMERIC,
    Total_Assets NUMERIC,
    Payables_and_Accruals NUMERIC,
    Short_Term_Debt NUMERIC,
    Total_Current_Liabilities NUMERIC,
    Long_Term_Debt NUMERIC,
    Total_Noncurrent_Liabilities NUMERIC,
    Total_Liabilities NUMERIC,
    Share_Capital_and_Additional_Paid_In_Capital NUMERIC,
    Treasury_Stock NUMERIC,
    Retained_Earnings NUMERIC,
    Total_Equity NUMERIC,
    Total_Liabilities_and_Equity NUMERIC,
    FOREIGN KEY (Company_ID) REFERENCES US_Companies (Company_ID)
);

CREATE INDEX idx_company_id_income ON income_statement (Company_ID);
CREATE INDEX idx_company_id_balance ON Balance_Sheet (Company_ID);